/* md5: 8c22bd645ad22b755b983dff7a0198c7 */
/* Rap repository id: 286 */
/* @infra/generation version: 0.0.1 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: ./repository/editor?id=286
 */

export interface IModels {
  'GET/test1': {
    Req: IModels['GET/test1']['Header'] &
      IModels['GET/test1']['Query'] &
      IModels['GET/test1']['Body'];
    Header: {};
    Query: {
      foo?: string;
      __scene?: string;
    };
    Body: {};
    Res: {
      foo?: string;
    };
  };
  'GET/test2': {
    Req: IModels['GET/test2']['Header'] &
      IModels['GET/test2']['Query'] &
      IModels['GET/test2']['Body'];
    Header: {};
    Query: {
      foo?: string;
      __scene?: string;
    };
    Body: {};
    Res: {
      foo?: string;
    };
  };
  'GET/test/random': {
    Req: IModels['GET/test/random']['Header'] &
      IModels['GET/test/random']['Query'] &
      IModels['GET/test/random']['Body'];
    Header: {};
    Query: {
      foo?: string;
      __scene?: string;
    };
    Body: {};
    Res: {
      foo?: number;
    };
  };
  'GET/error': {
    Req: IModels['GET/error']['Header'] &
      IModels['GET/error']['Query'] &
      IModels['GET/error']['Body'];
    Header: {};
    Query: {
      foo?: string;
      __scene?: string;
    };
    Body: {};
    Res: {};
  };
  'POST/test2': {
    Req: IModels['POST/test2']['Header'] &
      IModels['POST/test2']['Query'] &
      IModels['POST/test2']['Body'];
    Header: {};
    Query: {};
    Body: {
      foo?: string;
      __scene?: string;
    };
    Res: {
      foo?: string;
    };
  };
  'POST/error': {
    Req: IModels['POST/error']['Header'] &
      IModels['POST/error']['Query'] &
      IModels['POST/error']['Body'];
    Header: {};
    Query: {};
    Body: {
      foo?: string;
      __scene?: string;
    };
    Res: {};
  };
  'GET/list': {
    Req: IModels['GET/list']['Header'] & IModels['GET/list']['Query'] & IModels['GET/list']['Body'];
    Header: {};
    Query: {
      limit?: number;
      offset?: number;
      __scene?: string;
    };
    Body: {};
    Res: {
      data: Array<{ id: number }>;
      cursor: number;
    };
  };
}
